#!/bin/sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
  . "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
  . "$HOME/.xprofile"
fi

ssh-agent dwm

# while true; do
#   # Log stderror to a file
#   dwm 2> ~/.cache/.dwm.log
#   # No error logging
#   dwm >/dev/null 2>&1
# done

# ssh-agent awesome
