#!/bin/zsh
# https://wiki.archlinux.org/title/XDG_Base_Directory
# User directories
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_RUNTIME_DIR="/run/user/$UID"

# Vim
export VIMINIT='let $MYVIMRC = !has("nvim") ? "$XDG_CONFIG_HOME/vim/vimrc" : "$XDG_CONFIG_HOME/nvim/init.lua" | so $MYVIMRC'

# Bash
export BASH_COMPLETION_USER_FILE="$XDG_CONFIG_HOME/bash-completion/bash_completion"

# Rust
## Rustup
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
## Cargo
export CARGO_HOME="$XDG_DATA_HOME/cargo"

# Ruby
## RubyGems
export GEM_HOME="$XDG_DATA_HOME/gem"
export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"

# GNUPGHOME https://wiki.archlinux.org/title/GnuPG
export GNUPGHOME="$XDG_DATA_HOME/gnupg"

# Node
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"

# XINITRC
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export XSERVERRC="$XDG_CONFIG_HOME/X11/xserverrc"

# notmuch https://notmuchmail.org/
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
# inputrc https://wiki.archlinux.org/title/Readline
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/inputrc"
# GTK
export GTK2_RC_FILES="XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"

# export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KODI_DATA="$XDG_DATA_HOME/kodi"
#export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANSIBLE_CONFIG="XDG_CONFIG_HOME/ansible/ansible.cfg"

# Zsh
## oh-my-zsh
export ZSH="$XDG_DATA_HOME/oh-my-zsh"
## zsh
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
## zcompdump
export ZSH_COMPDUMP="$XDG_CACHE_HOME/zsh/.zcompdump-${SHORT_HOST}-${ZSH_VERSION}"

# Node
## nvm
export NVM_DIR="$XDG_DATA_HOME/nvm"
## npm
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
export NPM_CONFIG_TMP="$XDG_RUNTIME_DIR/npm"

# Go
export GOPATH="$XDG_DATA_HOME/go"
# Android
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
# Password-store
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
# Wget
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
# Unison & History
export UNISON="$XDG_DATA_HOME/unison"
export HISTFILE="$XDG_DATA_HOME/history"
# weechat
export WEECHAT_HOME="$XDG_CONFIG_HOME/weechat"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
