# XDG Base Directories
XDG_CONFIG_HOME=%h/.config
XDG_CACHE_HOME=%h/.cache
XDG_DATA_HOME=%h/.local/share
XDG_STATE_HOME=%h/.local/state

# Languages & Runtimes
CARGO_HOME=%h/.local/share/cargo
RUSTUP_HOME=%h/.local/share/rustup
GOPATH=%h/.local/share/go
PYENV_ROOT=%h/.local/share/pyenv
BUN_INSTALL=%h/.local/share/bun
NVM_DIR=%h/.local/share/nvm
GEM_HOME=%h/.local/share/gem
GEM_SPEC_CACHE=%h/.cache/gem
NODE_REPL_HISTORY=%h/.local/share/node_repl_history

# Applications
GNUPGHOME=%h/.local/share/gnupg
PASSWORD_STORE_DIR=%h/.local/share/password-store
WINEPREFIX=%h/.local/share/wineprefixes/default
KODI_DATA=%h/.local/share/kodi
ELECTRUMDIR=%h/.local/share/electrum
UNISON=%h/.local/share/unison
ANDROID_SDK_HOME=%h/.config/android
WEECHAT_HOME=%h/.config/weechat
MBSYNCRC=%h/.config/mbsync/config
WGETRC=%h/.config/wget/wgetrc
NOTMUCH_CONFIG=%h/.config/notmuch-config
VSCODE_PORTABLE=%h/.local/share/vscode
MPLAYER_HOME=%h/.config/mplayer
ANSIBLE_CONFIG=%h/.config/ansible/ansible.cfg
GTK2_RC_FILES=%h/.config/gtk-2.0/gtkrc-2.0
BASH_COMPLETION_USER_FILE=%h/.config/bash-completion/bash_completion
