# keymap.toml
[mgr]
prepend_keymap = [
  # goto
  { on = [
    "g",
    "w",
  ], run = "cd ~/.local/work/", desc = "Go to the work directory" },
  { on = [
    "g",
    "D",
  ], run = "cd /mnt/d/Users/liuxian/Downloads/", desc = "Go to the windows Downloads directory" },
]
