# keymap.toml
[manager]
prepend_keymap = [
  # ...
  { on = [
    "z",
    "h",
  ], run = "hidden toggle", desc = "Toggle the visibility of hidden files" },

  # { on = [
  #   "o",
  # ], run = 'help', desc = "Toggle the visibility of hidden files" },

  # goto
  { on = [
    "g",
    "w",
  ], run = "cd ~/.local/work/", desc = "Go to the work directory" },
]
